
server:
  port: 8483

spring:
  application:
    name: Drivz-CommonLibrary
  
  # configuration of database 
  datasource:
    url: jdbc:mysql://localhost:3306/drivz_db
    username: root
    password: Seraj@123
  jpa:
    hibernate:
      ddl-auto: validate
    
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  #    defer-datasource-initialization: true
  
  # configuration of flyway for database migration 
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/drivz_db
    user: root
    password: Seraj@123
    locations:
      - classpath:db/migration
